<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources/logo_and_script.png" />
    <Resource Include="Resources/logo_fullsize.png" />
    <Resource Include="Resources/logo_fullsize_backgrnd.png" />
    <Resource Include="Resources/logo_smaller.png" />
    <Resource Include="Resources/logo_smaller.ico" />
    <Resource Include="Resources/script.png" />
    <Resource Include="Resources/splash_background.png" />
  </ItemGroup>
  
</Project>
